#!/usr/bin/env python3
"""Merge upstream home-assistant-voice-pe YAML with device-connect patches.

Writes firmware/esphome/device-connect-voice.full.yaml

Usage:
  python scripts/merge_voice_pe_yaml.py
  python scripts/merge_voice_pe_yaml.py --upstream-url URL --upstream-ref dev
"""

from __future__ import annotations

import argparse
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "firmware" / "esphome" / "device-connect-voice.full.yaml"
DEFAULT_UPSTREAM = (
    "https://raw.githubusercontent.com/esphome/home-assistant-voice-pe/dev/home-assistant-voice.yaml"
)

HEADER = """# Merged Home Assistant Voice PE + Device Connect
#
# Generated by scripts/merge_voice_pe_yaml.py — do not edit by hand; re-run the script.
# Upstream: esphome/home-assistant-voice-pe @ {ref}
#   {url}
#
# Flash:
#   cp firmware/secrets.yaml.example firmware/esphome/secrets.yaml  # edit wifi (+ portal Phase 2)
#   cd firmware/esphome && esphome compile device-connect-voice.full.yaml
#   cd firmware/esphome && esphome upload device-connect-voice.full.yaml --device /dev/cu.usbmodem1101
#
# Portal NATS (Phase 2): device_connect component still stub — secrets reserved in secrets.yaml.example

"""

DC_SUBSTITUTIONS = """
  # Device Connect (device-connect-voice)
  dc_device_id: erivan01-voice
  dc_tenant: erivan01
  # Empty = Zenoh peer/D2D (multicast). Set tcp/192.168.x.x:7447 for a LAN router.
  dc_zenoh_connect: ""
"""

DC_EXTERNAL_COMPONENT = """
  - source:
      type: local
      path: ../components
    components:
      - device_connect
"""

DC_GLOBAL = """
  # Device Connect: last STT text for get_last_transcript RPC (Phase 1 wiring)
  - id: dc_last_transcript
    type: std::string
    restore_value: no
    initial_value: '""'
"""

DC_WIFI = """
  ssid: !secret wifi_ssid
  password: !secret wifi_password
"""

DC_BLOCK = """
# Device Connect edge driver (Zenoh/NATS transport — Phase 1+)
device_connect:
  id: dc
  device_id: ${dc_device_id}
  tenant: ${dc_tenant}
  enabled: true
  zenoh_connect: ${dc_zenoh_connect}
  zenoh_enabled: true
  stt_backend: voice_assistant
  voice_assistant_phase_id: voice_assistant_phase
  last_transcript_id: dc_last_transcript
  color_changed_id: color_changed
  voice_assistant_id: va
  micro_wake_word_id: mww
  wake_word_sensitivity_id: wake_word_sensitivity
  center_button_id: center_button
  master_mute_switch_id: master_mute_switch
  media_player_id: external_media_player
  led_light_id: voice_assistant_leds
  control_volume_script_id: control_volume
  control_leds_script_id: control_leds
  play_sound_script_id: play_sound
"""

DC_VOICE_HOOKS = """
  on_stt_end:
    - lambda: |-
        id(dc_last_transcript) = x;
        id(dc).on_stt_text(x);
"""

DC_MWW_HOOK = """
    - lambda: 'id(dc).on_wake_word_detected(wake_word);'
"""


def fetch_upstream(url: str) -> str:
    with urllib.request.urlopen(url, timeout=60) as resp:
        return resp.read().decode("utf-8")


def merge(text: str, *, upstream_ref: str, upstream_url: str) -> str:
    # Wi-Fi: ESPHome 2026.5+ requires ssid/password (upstream improv-only wifi block fails config)
    if "!secret wifi_ssid" not in text:
        text = text.replace(
            "wifi:\n  id: wifi_id\n",
            "wifi:\n  id: wifi_id\n" + DC_WIFI,
            1,
        )

    # Substitutions: insert before closing of substitutions block (line before esphome:)
    if "dc_device_id:" in text:
        raise SystemExit("upstream already contains dc_device_id — merge manually or refresh base")

    text = re.sub(
        r"(?m)^(esphome:)",
        DC_SUBSTITUTIONS + r"\1",
        text,
        count=1,
    )

    # external_components: append local device_connect after voice_kit git block
    if "components:\n      - device_connect" not in text:
        text = text.replace(
            "    refresh: 0s\n\naudio_dac:",
            "    refresh: 0s\n" + DC_EXTERNAL_COMPONENT + "\naudio_dac:",
            1,
        )

    # globals: after voice_assistant_phase entry block (after its initial_value line)
    if "dc_last_transcript" not in text:
        text = text.replace(
            "    initial_value: ${voice_assist_not_ready_phase_id}\n",
            "    initial_value: ${voice_assist_not_ready_phase_id}\n" + DC_GLOBAL,
            1,
        )

    # device_connect block before micro_wake_word
    if "device_connect:" not in text:
        text = text.replace(
            "micro_wake_word:",
            DC_BLOCK + "\nmicro_wake_word:",
            1,
        )

    if "on_stt_end:" not in text and "voice_assistant:\n" in text:
        text = text.replace(
            "  on_stt_vad_start:",
            DC_VOICE_HOOKS + "  on_stt_vad_start:",
            1,
        )

    if "id(dc).on_wake_word_detected" not in text:
        text = text.replace(
            "  on_wake_word_detected:\n",
            "  on_wake_word_detected:\n" + DC_MWW_HOOK,
            1,
        )

    header = HEADER.format(ref=upstream_ref, url=upstream_url)
    return header + text


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--upstream-url", default=DEFAULT_UPSTREAM)
    parser.add_argument("--upstream-ref", default="dev")
    parser.add_argument("-o", "--output", type=Path, default=OUT)
    args = parser.parse_args()

    text = fetch_upstream(args.upstream_url)
    merged = merge(text, upstream_ref=args.upstream_ref, upstream_url=args.upstream_url)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(merged, encoding="utf-8")
    print(f"Wrote {args.output} ({len(merged.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
